import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useRef } from "react";

export default function Search({ type }) {
  const inputRef = useRef();
  const [results, setResults] = useState(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.searchArea}>
          <input className={styles.input} ref={inputRef} />
          <button
            type="button"
            onClick={() => {
              const getParams = new URLSearchParams();

              getParams.set("q", inputRef.current.value);

              if (type) {
                getParams.set("type", type);
              }

              fetch(`/api/search?${getParams}`)
                .then((response) => {
                  return response.json();
                })
                .then((json) => {
                  setResults(json);
                });
            }}
          >
            Search
          </button>
        </div>
        {results && (
          <div>
            {results.map((item, index) => {
              const { date, link, title, thumbnail, snippet } = item;
              return (
                <div key={index} className={styles.item}>
                  {thumbnail && (
                    <div className={styles.image}>
                      <img src={thumbnail} />
                    </div>
                  )}
                  <div className={styles.itemText}>
                    {date && <div className={styles.date}>{date}</div>}
                    <div className={styles.title}>
                      <a href={link}>{title}</a>
                    </div>
                    {snippet && <p>{snippet}</p>}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>
    </div>
  );
}
